test:
    benchmark:
        all: false
    httpTest:
        all: false
    loop:
        all: false
    regex:
        all: false
    midtrans:
        all: false
    number:
        all: false
midtrans:
    clientKey: ""
    serverKey: ""
    productionMode: false
